name: franfeldman
favicon: null
layout_spectrum: 0.8761503254063427
typography_spectrum: 0.9072114275768399
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.26083863945677876
  lightness: 0.0819372939877212
  saturation: 0.16939572873525321
  rhythmicContrast: 0.08488621492870152
purpose: []
